export const LOAD_USER = "LOAD_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const LOGIN_SUCCESS = "LOGIN_SUCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION"

export const LIST_USER_ACCOUNTS = 'LIST_USER_ACCOUNTS'
export const CLEAR_LIST_USERACCOUNTS = 'CLEAR_LIST_USERACCOUNTS'
export const LIST_EMPLOYEES = 'LIST_EMPLOYEES'